name: Publish to Docker Registry

on:
  push:
    branches:
      - publishing-docker-image
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build and Push Docker Image
        run: sbt Docker/publish
